# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: true
tone_instructions: >-
  Concise, direct, security-aware. This is a security scanner — flag
  anything that could weaken scan accuracy, leak credentials, or
  introduce false negatives. No fluff.

reviews:
  profile: "assertive"
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_in_walkthrough: true
  poem: false
  in_progress_fortune: false
  sequence_diagrams: true
  collapse_walkthrough: false
  changed_files_summary: true
  review_status: true
  commit_status: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: true
  suggested_reviewers: false
  auto_apply_labels: false
  enable_prompt_for_ai_agents: true

  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"

  path_filters:
    - "!**/__pycache__/**"
    - "!**/.mypy_cache/**"
    - "!**/.ruff_cache/**"
    - "!**/.pytest_cache/**"

  path_instructions:
    - path: "src/counteragent/audit/scanner/**"
      instructions: >-
        Vulnerability scanning logic. Verify: scan coverage maps to
        OWASP MCP Top 10 categories. Check that evidence collection
        is deterministic and reproducible. Flag any scanner that
        silently swallows exceptions — false negatives are worse
        than false positives.
    - path: "src/counteragent/audit/payloads/**"
      instructions: >-
        Test payloads for vulnerability detection. Verify payloads
        are inert (detection-only, not exploitation). Check that
        payload metadata includes OWASP category mapping.
    - path: "src/counteragent/audit/reporting/**"
      instructions: >-
        Scan report generation. Verify: no raw credentials in
        reports, evidence is properly attributed, OWASP mappings
        are accurate. Check output formats are valid.
    - path: "src/counteragent/proxy/**"
      instructions: >-
        MCP proxy interceptor. Security-critical — verify: no
        credential leakage in intercepted traffic logs, session
        isolation between concurrent scans, replay functionality
        doesn't modify original payloads.
    - path: "src/counteragent/core/**"
      instructions: >-
        Core models and transport. Verify: evidence models are
        immutable after creation, OWASP mappings are complete,
        transport layer handles connection failures gracefully.
        Check cross-platform path handling (pathlib).
    - path: "fixtures/**"
      instructions: >-
        Vulnerable server fixtures for testing. Verify: fixtures
        contain only intentional vulnerabilities, no real credentials,
        clear documentation of what each fixture tests.
    - path: "tests/**"
      instructions: >-
        Test suite. Verify: no real MCP server connections, mock
        all external calls. Check cross-platform compatibility.
        Ensure fixtures don't contain real API keys.
    - path: ".github/workflows/**"
      instructions: >-
        CI/CD workflows. Check: secrets not exposed in logs, matrix
        includes both ubuntu-latest and windows-latest where appropriate,
        and action versions are sensibly pinned (major tag like v4 or
        commit SHA). Do not flag existing tag-based pins as issues.

  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true

  tools:
    ruff:
      enabled: true
    gitleaks:
      enabled: true
    trufflehog:
      enabled: true
    actionlint:
      enabled: true
    shellcheck:
      enabled: true
    yamllint:
      enabled: true
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 120000

chat:
  auto_reply: true

knowledge_base:
  code_guidelines:
    enabled: true
  learnings:
    scope: "local"
  issues:
    scope: "local"
  pull_requests:
    scope: "local"
  web_search:
    enabled: true
  linked_repositories:
    - repository: "q-uestionable-ai/mutual-dissent"
      instructions: >-
        Cross-vendor multi-model debate engine. Shares research
        methodology patterns. Debate transcripts may reference
        CounterAgent scan findings in research documentation.
    # Uncomment once CounterSignal repo exists on GitHub:
    # - repository: "q-uestionable-ai/countersignal"
    #   instructions: >-
    #     Adversarial payload generator. CounterAgent discovers
    #     vulnerabilities, CounterSignal generates payloads to
    #     test them. Shared evidence models and OWASP mappings.

code_generation:
  docstrings:
    language: "en-US"
    path_instructions:
      - path: "**/*.py"
        instructions: >-
          Use Google-style docstrings. Include Args, Returns, and Raises
          sections. Keep descriptions concise — one line for simple
          functions, brief paragraph for complex ones.
  unit_tests:
    path_instructions:
      - path: "src/**/*.py"
        instructions: >-
          Use pytest with pytest-asyncio for async tests. Mock all
          external MCP server connections. Use fixtures from conftest.py.
          Tests must pass on both Windows and Linux.
